apiVersion: v1
kind: ConfigMap
metadata:
  name: pedidos-config
data:
  DB_HOST: "postgres"
  DB_NAME: "pedidos_db"
  DB_USER: "veloz_user"
  RABBITMQ_URL: "amqp://rabbitmq-service:5672"
---
apiVersion: v1
kind: Secret
metadata:
  name: pedidos-secret
type: Opaque
stringData:
  
  DB_PASSWORD: "local_password"